# 配置RabbitMQ的基本信息  ip 端口 username  password..
spring:
  rabbitmq:
    host: 127.0.0.1 # ip
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true  #开启接收消息消费回调，默认是false，需要开启，mq才会回调

server:
  port: 8888